//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arnolyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arnolyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide encapsulation, properties should only make getters publicly available, so interfaces should not define setters for properties..
        /// </summary>
        public static string AA1102InterfacePropertiesMustBeReadOnlyDescription {
            get {
                return ResourceManager.GetString("AA1102InterfacePropertiesMustBeReadOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property `{0}` of interface `{1}` should not define a setter.
        /// </summary>
        public static string AA1102InterfacePropertiesMustBeReadOnlyMessageFormat {
            get {
                return ResourceManager.GetString("AA1102InterfacePropertiesMustBeReadOnlyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA1102-InterfacePropertiesMustBeReadOnly.
        /// </summary>
        public static string AA1102InterfacePropertiesMustBeReadOnlyTitle {
            get {
                return ResourceManager.GetString("AA1102InterfacePropertiesMustBeReadOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public classes should not provide publicly accessible setters for properties.
        /// </summary>
        public static string AA1103ClassPropertiesMustBePubliclyReadOnlyDescription {
            get {
                return ResourceManager.GetString("AA1103ClassPropertiesMustBePubliclyReadOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public property `{0}` of class `{1}` should not define a public setter.
        /// </summary>
        public static string AA1103ClassPropertiesMustBePubliclyReadOnlyMessageFormat {
            get {
                return ResourceManager.GetString("AA1103ClassPropertiesMustBePubliclyReadOnlyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA1103-ClassPropertiesMustBePubliclyReadOnly.
        /// </summary>
        public static string AA1103ClassPropertiesMustBePubliclyReadOnlyTitle {
            get {
                return ResourceManager.GetString("AA1103ClassPropertiesMustBePubliclyReadOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner types should be treated as implementation details and encapsulated by marking them as private.
        /// </summary>
        public static string AA1104InnerTypesMustBePrivateDescription {
            get {
                return ResourceManager.GetString("AA1104InnerTypesMustBePrivateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` is defined inside another type, so should be made private.
        /// </summary>
        public static string AA1104InnerTypesMustBePrivateMessageFormat {
            get {
                return ResourceManager.GetString("AA1104InnerTypesMustBePrivateMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA1104-InnerTypesMustBePrivate.
        /// </summary>
        public static string AA1104InnerTypesMustBePrivateTitle {
            get {
                return ResourceManager.GetString("AA1104InnerTypesMustBePrivateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotImplementedException is a direct violation of the Liskov Substitution Principle (LSP) and so must not be used.
        /// </summary>
        public static string DoNotUseNotImplementedExceptionDescription {
            get {
                return ResourceManager.GetString("DoNotUseNotImplementedExceptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw statement uses the NotImplementedException, which is a violation of the LSP.
        /// </summary>
        public static string DoNotUseNotImplementedExceptionMessageFormat {
            get {
                return ResourceManager.GetString("DoNotUseNotImplementedExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotImplementedException violates the Liskov Substitution Principle (LSP).
        /// </summary>
        public static string DoNotUseNotImplementedExceptionTitle {
            get {
                return ResourceManager.GetString("DoNotUseNotImplementedExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotSupportedException is a direct violation of the Liskov Substitution Principle (LSP) and so must not be used.
        /// </summary>
        public static string DoNotUseNotSupportedExceptionDescription {
            get {
                return ResourceManager.GetString("DoNotUseNotSupportedExceptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw statement uses the NotSupportedException, which is a violation of the LSP.
        /// </summary>
        public static string DoNotUseNotSupportedExceptionMessageFormat {
            get {
                return ResourceManager.GetString("DoNotUseNotSupportedExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotSupportedException violates the Liskov Substitution Principle (LSP).
        /// </summary>
        public static string DoNotUseNotSupportedExceptionTitle {
            get {
                return ResourceManager.GetString("DoNotUseNotSupportedExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To comply with the single responsibility principle, a file should only contain one non-private type definition..
        /// </summary>
        public static string FileMustOnlyContainOneTypeDefinitionDescription {
            get {
                return ResourceManager.GetString("FileMustOnlyContainOneTypeDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` is located in a file that contains other type definitions.
        /// </summary>
        public static string FileMustOnlyContainOneTypeDefinitionMessageFormat {
            get {
                return ResourceManager.GetString("FileMustOnlyContainOneTypeDefinitionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file should only contain one type definition.
        /// </summary>
        public static string FileMustOnlyContainOneTypeDefinitionTitle {
            get {
                return ResourceManager.GetString("FileMustOnlyContainOneTypeDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method parameters must not use REF or OUT parameters; all results should be via a return.
        /// </summary>
        public static string MethodParameterMustNotBeRefOrOutDescription {
            get {
                return ResourceManager.GetString("MethodParameterMustNotBeRefOrOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter `{0}` of method `{1}` must not use {2}.
        /// </summary>
        public static string MethodParameterMustNotBeRefOrOutMessageFormat {
            get {
                return ResourceManager.GetString("MethodParameterMustNotBeRefOrOutMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method parameters must not  use REF or OUT.
        /// </summary>
        public static string MethodParameterMustNotBeRefOrOutTitle {
            get {
                return ResourceManager.GetString("MethodParameterMustNotBeRefOrOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method names that contain &quot;And&quot; often indicate a method is doing more than one thing. Consider refacting into two methods..
        /// </summary>
        public static string MethodShouldNotContainAndDescription {
            get {
                return ResourceManager.GetString("MethodShouldNotContainAndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; contains &quot;And&quot;, which might indicate it&apos;s doing more than one thing.
        /// </summary>
        public static string MethodShouldNotContainAndMessageFormat {
            get {
                return ResourceManager.GetString("MethodShouldNotContainAndMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods should not contain the word &quot;And&quot;.
        /// </summary>
        public static string MethodShouldNotContainAndTitle {
            get {
                return ResourceManager.GetString("MethodShouldNotContainAndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static methods should have at least one parameter.
        /// </summary>
        public static string StaticMethodMustHaveAtLeastOneParameterDescription {
            get {
                return ResourceManager.GetString("StaticMethodMustHaveAtLeastOneParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static method &apos;{0}&apos; doesn&apos;t have any parameters. It should have at least one.
        /// </summary>
        public static string StaticMethodMustHaveAtLeastOneParameterMessageFormat {
            get {
                return ResourceManager.GetString("StaticMethodMustHaveAtLeastOneParameterMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static methods must have at least one parameter.
        /// </summary>
        public static string StaticMethodMustHaveAtLeastOneParameterTitle {
            get {
                return ResourceManager.GetString("StaticMethodMustHaveAtLeastOneParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static methods should return a value (must not be null).
        /// </summary>
        public static string StaticMethodMustNotBeVoidDescription {
            get {
                return ResourceManager.GetString("StaticMethodMustNotBeVoidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static method &apos;{0}&apos; is void. It should return a value.
        /// </summary>
        public static string StaticMethodMustNotBeVoidMessageFormat {
            get {
                return ResourceManager.GetString("StaticMethodMustNotBeVoidMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static methods must not be void.
        /// </summary>
        public static string StaticMethodMustNotBeVoidTitle {
            get {
                return ResourceManager.GetString("StaticMethodMustNotBeVoidTitle", resourceCulture);
            }
        }
    }
}
