//

// <auto-generated>
//
// </auto-generated>
namespace Arnolyzer.Test.CodeUnderTest
{
    public static class AutogeneratedStaticVoidCode
    {
        public static void DoNothing() { }

        public static bool ReturnTrue() => true;

        public static void StillDoNothing() { }
    }
}