using Arnolyzer.Analyzers.GlobalStateAnalyzers;
using Arnolyzer.Tests.DiagnosticVerification;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SuccincT.Options;
using static System.String;

namespace Arnolyzer.Tests.Analyzers.GlobalStateAnalyzers
{
    [TestClass]
    public class AA1200AvoidUsingStaticFieldsAnalyzerTests
    {
        [TestMethod]
        public void NoCode_ShouldYieldNoDiagnostics() =>
            DiagnosticVerifier.VerifyDiagnostics<AA1200AvoidUsingStaticFieldsAnalyzer>(
                @"..\..\CodeUnderTest\EmptyFile.cs");

        [TestMethod]
        public void IgnoredCode_ShouldYieldNoDiagnostics() =>
            DiagnosticVerifier.VerifyDiagnostics<AA1200AvoidUsingStaticFieldsAnalyzer>(
                @"..\..\CodeUnderTest\AutogeneratedFieldsAndProperties.cs");

        [TestMethod]
        public void InterfacePropertiesWithSetters_YieldsDiagnostics()
        {
            var commonExpected =
                new DiagnosticResultCommonProperties(new AA1200AvoidUsingStaticFieldsAnalyzer());

            var expected1 =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1200AvoidUsingStaticFieldsMessageFormat,
                                            "A2",
                                            "CodeToTestAvoidUsingStaticFieldsAndProperties"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(8, 27, 29)));

            var expected2 =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1200AvoidUsingStaticFieldsMessageFormat,
                                            "B2",
                                            "CodeToTestAvoidUsingStaticFieldsAndProperties"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(12, 28, 30)));

            var expected3 =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1200AvoidUsingStaticFieldsMessageFormat,
                                            "C2",
                                            "CodeToTestAvoidUsingStaticFieldsAndProperties"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(16, 29, 31)));

            var expected4 =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1200AvoidUsingStaticFieldsMessageFormat,
                                            "D2",
                                            "CodeToTestAvoidUsingStaticFieldsAndProperties"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(20, 30, 32)));

            DiagnosticVerifier.VerifyDiagnostics<AA1200AvoidUsingStaticFieldsAnalyzer>(
                @"..\..\CodeUnderTest\CodeToTestAvoidUsingStaticFieldsAndProperties.cs",
                expected1,
                expected2,
                expected3,
                expected4);
        }
    }
}