using Arnolyzer.Analyzers.GlobalStateAnalyzers;
using Arnolyzer.Tests.DiagnosticVerification;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SuccincT.Options;
using static System.String;

namespace Arnolyzer.Tests.Analyzers.GlobalStateAnalyzers
{
    [TestClass]
    public class AA1201AvoidUsingStaticPropertiesAnalyzerTests
    {
        [TestMethod]
        public void NoCode_ShouldYieldNoDiagnostics() =>
            DiagnosticVerifier.VerifyDiagnostics<AA1201AvoidUsingStaticPropertiesAnalyzer>(
                @"..\..\CodeUnderTest\EmptyFile.cs");

        [TestMethod]
        public void IgnoredCode_ShouldYieldNoDiagnostics() =>
            DiagnosticVerifier.VerifyDiagnostics<AA1201AvoidUsingStaticPropertiesAnalyzer>(
                @"..\..\CodeUnderTest\AutogeneratedFieldsAndProperties.cs");

        [TestMethod]
        public void InterfacePropertiesWithSetters_YieldsDiagnostics()
        {
            var commonExpected =
                new DiagnosticResultCommonProperties(new AA1201AvoidUsingStaticPropertiesAnalyzer());

            var expected1 =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1201AvoidUsingStaticPropertiesMessageFormat,
                                            "PropA1",
                                            "CodeToTestAvoidUsingStaticFieldsAndProperties"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(33, 27, 33)));

            var expected2 =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1201AvoidUsingStaticPropertiesMessageFormat,
                                            "PropB1",
                                            "CodeToTestAvoidUsingStaticFieldsAndProperties"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(34, 29, 35)));

            var expected3 =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1201AvoidUsingStaticPropertiesMessageFormat,
                                            "PropC1",
                                            "CodeToTestAvoidUsingStaticFieldsAndProperties"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(35, 28, 34)));

            var expected4 =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1201AvoidUsingStaticPropertiesMessageFormat,
                                            "PropD1",
                                            "CodeToTestAvoidUsingStaticFieldsAndProperties"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(36, 30, 36)));

            DiagnosticVerifier.VerifyDiagnostics<AA1201AvoidUsingStaticPropertiesAnalyzer>(
                @"..\..\CodeUnderTest\CodeToTestAvoidUsingStaticFieldsAndProperties.cs",
                expected1,
                expected2,
                expected3,
                expected4);
        }
    }
}