// <auto-generated>
namespace Arnolyzer.Tests.CodeUnderTest
{
    public class AutogeneratedFieldsAndProperties
    {
        public static int A;
        private static int B;
        internal static int C;
        protected static int D;

        public int BP { get { return B; } set { B = value; } }
        public int CP { get { return C; } set { C = value; } }
        public static int AProp { get { return A; } set { A = value; } }
        public static int BProp { get { return B; } set { B = value; } }
        public static int CProp { get { return C; } set { C = value; } }
        public static int DProp { get { return D; } set { D = value; } }
    }
}
