//

//

// <auto-generated>
namespace Arnolyzer.Tests.CodeUnderTest
{
    public static class AutogeneratedNoParameterCode
    {
        public static bool ReturnTrue() => true;

        public static bool ReturnsSelf(bool flag) => flag;
    }
}