using Arnolyzer.SyntacticAnalyzers.SHOFAnalyzers;
using Arnolyzer.Tests.DiagnosticVerification;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SuccincT.Options;
using static System.String;
using static Arnolyzer.Tests.SyntacticAnalyzers.TestFiles;

namespace Arnolyzer.Tests.SyntacticAnalyzers.SHOFAnalyzersTests
{
    [TestClass]
    public class AA1001StaticMethodsMustHaveAtLeastOneParameterAnalyzerTests
    {
        [TestMethod]
        public void NoCode_ShouldYieldNoDiagnostics() =>
            DiagnosticVerifier.VerifyDiagnostics<AA1001StaticMethodsMustHaveAtLeastOneParameterAnalyzer>(EmptyFile);

        [TestMethod]
        public void StaticMethodWithNoParams_YieldsADiagnostic()
        {
            var commonExpected =
                new DiagnosticResultCommonProperties(new AA1001StaticMethodsMustHaveAtLeastOneParameterAnalyzer());
            var expected =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1001StaticMethodsMustHaveAtLeastOneParameterMessageFormat,
                                            "ReturnTrue"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(5, 28, 38)));

            DiagnosticVerifier.VerifyDiagnostics<AA1001StaticMethodsMustHaveAtLeastOneParameterAnalyzer>(
                CodeToTestAtLeastOneParameterAnalyzer,
                expected);
        }

        [TestMethod]
        public void StaticMethodWithNoParamsInGeneratedCode_YieldsNoDiagnostics()
        {
            DiagnosticVerifier.VerifyDiagnostics<AA1001StaticMethodsMustHaveAtLeastOneParameterAnalyzer>(
                AutogeneratedNoParameterCode);
        }

        [TestMethod]
        public void CodeWithStaticGetters_YieldsNoDiagnostics()
        {
            DiagnosticVerifier.VerifyDiagnostics<AA1001StaticMethodsMustHaveAtLeastOneParameterAnalyzer>(
                CodeToTestAtLeastOneParameterAnalyzerIgnoresGetters);
        }

        [TestMethod]
        public void TwoStaticMethodsWithNoParamsOneWithAttribute_YieldsOneDiagnostic()
        {
            var commonExpected =
                new DiagnosticResultCommonProperties(new AA1001StaticMethodsMustHaveAtLeastOneParameterAnalyzer());
            var expected =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.AA1001StaticMethodsMustHaveAtLeastOneParameterMessageFormat,
                                            "ReturnTrue"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(8, 28, 38)));

            DiagnosticVerifier.VerifyDiagnostics<AA1001StaticMethodsMustHaveAtLeastOneParameterAnalyzer>(
                CodeToTestAtLeastOneParameterAnalyzerRespectsAttributes,
                expected);
        }
    }
}