using Arnolyzer.SyntacticAnalyzers;
using Arnolyzer.SyntacticAnalyzers.SHOFAnalyzers;
using Arnolyzer.Tests.DiagnosticVerification;
using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SuccincT.Options;
using static System.String;
using static Arnolyzer.Tests.SyntacticAnalyzers.TestFiles;

namespace Arnolyzer.Tests.SyntacticAnalyzers.SHOFAnalyzersTests
{
    [TestClass]
    public class StaticMethodMustHaveAtLeastOneParameterTests
    {
        [TestMethod]
        public void NoCode_ShouldYieldNoDiagnostics() =>
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(EmptyFile);

        [TestMethod]
        public void StaticMethodWithNoParams_YieldsADiagnostic()
        {
            var commonExpected =
                new DiagnosticResultCommonProperties(Resources.StaticMethodMustHaveAtLeastOneParameterTitle,
                                                     Resources.StaticMethodMustHaveAtLeastOneParameterDescription,
                                                     DiagnosticSeverity.Error,
                                                     AnalyzerCategories.ShofAnalyzers,
                                                     StaticMethodMustHaveAtLeastOneParameterAnalyzer.DiagnosticId);
            var expected =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.StaticMethodMustHaveAtLeastOneParameterMessageFormat,
                                            "ReturnTrue"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(5, 28, 38)));

            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(
                CodeToTestAtLeastOneParameterAnalyzer,
                expected);
        }

        [TestMethod]
        public void StaticMethodWithNoParamsInGeneratedCode_YieldsNoDiagnostics()
        {
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(
                AutogeneratedNoParameterCode);
        }

        [TestMethod]
        public void CodeWithStaticGetters_YieldsNoDiagnostics()
        {
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(
                CodeToTestAtLeastOneParameterAnalyzerIgnoresGetters);
        }

        [TestMethod]
        public void TwoStaticMethodsWithNoParamsOneWithAttribute_YieldsOneDiagnostic()
        {
            var commonExpected =
                new DiagnosticResultCommonProperties(Resources.StaticMethodMustHaveAtLeastOneParameterTitle,
                                                     Resources.StaticMethodMustHaveAtLeastOneParameterDescription,
                                                     DiagnosticSeverity.Error,
                                                     AnalyzerCategories.ShofAnalyzers,
                                                     StaticMethodMustHaveAtLeastOneParameterAnalyzer.DiagnosticId);
            var expected =
                new DiagnosticResult(commonExpected,
                                     Format(Resources.StaticMethodMustHaveAtLeastOneParameterMessageFormat,
                                            "ReturnTrue"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(8, 28, 38)));

            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(
                CodeToTestAtLeastOneParameterAnalyzerRespectsAttributes,
                expected);
        }
    }
}