using System;
using System.IO;
using Arnolyzer.SyntacticAnalyzers;
using Arnolyzer.SyntacticAnalyzers.SHOFAnalyzers;
using Arnolyzer.Tests.DiagnosticVerification;
using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SuccincT.Options;

namespace Arnolyzer.Tests.SyntacticAnalyzers.SHOFAnalyzersTests
{
    [TestClass]
    public class StaticMethodMustHaveAtLeastOneParameterTests
    {
        [TestMethod]
        public void NoCode_ShouldYieldNoDiagnostics() =>
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>("");

        [TestMethod]
        public void StaticMethodWithNoParams_YieldsADiagnostic()
        {
            var test = File.ReadAllText(@"..\..\CodeUnderTest\CodeToTestAtLeastOneParameterAnalyzer.cs");
            var commonExpected =
                new DiagnosticResultCommonProperties(Resources.StaticMethodMustHaveAtLeastOneParameterTitle,
                                                     Resources.StaticMethodMustHaveAtLeastOneParameterDescription,
                                                     DiagnosticSeverity.Error,
                                                     AnalyzerCategories.ShofAnalyzers,
                                                     StaticMethodMustHaveAtLeastOneParameterAnalyzer.DiagnosticId);
            var expected =
                new DiagnosticResult(commonExpected,
                                     String.Format(Resources.StaticMethodMustHaveAtLeastOneParameterMessageFormat,
                                            "ReturnTrue"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(5, 28, 38)));

            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(test, expected);
        }

        [TestMethod]
        public void StaticMethodWithNoParamsInGeneratedCode_YieldsNoDiagnostics()
        {
            var test = File.ReadAllText(@"..\..\CodeUnderTest\AutogeneratedNoParameterCode.cs");
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(test);
        }

        [TestMethod]
        public void CodeWithStaticGetters_YieldsNoDiagnostics()
        {
            var test = File.ReadAllText(@"..\..\CodeUnderTest\CodeToTestAtLeastOneParameterAnalyzerIgnoresGetters.cs");
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(test);
        }

        [TestMethod]
        public void TwoStaticMethodsWithNoParamsOneWithAttribute_YieldsOneDiagnostic()
        {
            var test =
                File.ReadAllText(@"..\..\CodeUnderTest\CodeToTestAtLeastOneParameterAnalyzerRespectsAttributes.cs");

            var commonExpected =
                new DiagnosticResultCommonProperties(Resources.StaticMethodMustHaveAtLeastOneParameterTitle,
                                                     Resources.StaticMethodMustHaveAtLeastOneParameterDescription,
                                                     DiagnosticSeverity.Error,
                                                     AnalyzerCategories.ShofAnalyzers,
                                                     StaticMethodMustHaveAtLeastOneParameterAnalyzer.DiagnosticId);
            var expected =
                new DiagnosticResult(commonExpected,
                                     String.Format(Resources.StaticMethodMustHaveAtLeastOneParameterMessageFormat,
                                            "ReturnTrue"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(8, 28, 38)));

            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustHaveAtLeastOneParameterAnalyzer>(test, expected);
        }
    }
}