using System;
using System.IO;
using Arnolyzer.SyntacticAnalyzers;
using Arnolyzer.SyntacticAnalyzers.SHOFAnalyzers;
using Arnolyzer.Tests.DiagnosticVerification;
using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SuccincT.Options;

namespace Arnolyzer.Tests.SyntacticAnalyzers.SHOFAnalyzersTests
{
    [TestClass]
    public class StaticMethodMustNotBeVoidAnalyzerTests
    {
        [TestMethod]
        public void NoCode_ShouldYieldNoDiagnostics() =>
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustNotBeVoidAnalyzer>("");

        [TestMethod]
        public void CodeWithTwoVoidMethods_YieldsTwoDiagnostics()
        {
            var test = File.ReadAllText(@"..\..\CodeUnderTest\CodeToTestStaticVoidAnalyzer.cs");
            var commonExpected = new DiagnosticResultCommonProperties(Resources.StaticMethodMustNotBeVoidTitle,
                                                                      Resources.StaticMethodMustNotBeVoidDescription,
                                                                      DiagnosticSeverity.Error,
                                                                      AnalyzerCategories.ShofAnalyzers,
                                                                      StaticMethodMustNotBeVoidAnalyzer.DiagnosticId);
            var expected1 =
                new DiagnosticResult(commonExpected,
                                     String.Format(Resources.StaticMethodMustNotBeVoidMessageFormat, "DoNothing"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(5, 28, 37)));

            var expected2 =
                new DiagnosticResult(commonExpected,
                                     String.Format(Resources.StaticMethodMustNotBeVoidMessageFormat, "StillDoNothing"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(8, 28, 42)));

            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustNotBeVoidAnalyzer>(test, expected1, expected2);
        }

        [TestMethod]
        public void AutogeneratedCode_YieldsNoDiagnostics()
        {
            var test = File.ReadAllText(@"..\..\CodeUnderTest\AutogeneratedStaticVoidCode.cs");
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustNotBeVoidAnalyzer>(test);
        }

        [TestMethod]
        public void CodeInIgnoredFile_YieldsNoDiagnostics()
        {
            var test = File.ReadAllText(@"..\..\CodeUnderTest\FileThatShouldBeIgnored.cs");
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustNotBeVoidAnalyzer>(test, @"..\..\arnolyzer.yaml");
        }

        [TestMethod]
        public void CodeWithSetters_YieldsNoDiagnostics()
        {
            var test = File.ReadAllText(@"..\..\CodeUnderTest\CodeToTestStaticVoidAnalyzerIgnoresSetters.cs");
            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustNotBeVoidAnalyzer>(test);
        }

        [TestMethod]
        public void CodeWithFourVoidMethodsTwoWithIgnoreRuleAttributes_YieldsTwoDiagnostic()
        {
            var test = File.ReadAllText(@"..\..\CodeUnderTest\CodeToTestStaticVoidAnalyzerRespectsAttributes.cs");
            var commonExpected = new DiagnosticResultCommonProperties(Resources.StaticMethodMustNotBeVoidTitle,
                                                                      Resources.StaticMethodMustNotBeVoidDescription,
                                                                      DiagnosticSeverity.Error,
                                                                      AnalyzerCategories.ShofAnalyzers,
                                                                      StaticMethodMustNotBeVoidAnalyzer.DiagnosticId);
            var expected1 =
                new DiagnosticResult(commonExpected,
                                     String.Format(Resources.StaticMethodMustNotBeVoidMessageFormat, "DoNothing1"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(8, 28, 38)));

            var expected2 =
                new DiagnosticResult(commonExpected,
                                     String.Format(Resources.StaticMethodMustNotBeVoidMessageFormat, "DoNothing4"),
                                     Option<DiagnosticLocation>.Some(new DiagnosticLocation(17, 28, 38)));

            DiagnosticVerifier.VerifyDiagnostics<StaticMethodMustNotBeVoidAnalyzer>(test, expected1, expected2);
        }
    }
}