namespace Arnolyzer.Tests.SyntacticAnalyzers
{
    internal static class TestFiles
    {
        public const string EmptyFile = @"..\..\CodeUnderTest\EmptyFile.cs";

        public const string CodeToTestAtLeastOneParameterAnalyzer =
            @"..\..\CodeUnderTest\CodeToTestAtLeastOneParameterAnalyzer.cs";

        public const string AutogeneratedNoParameterCode =
            @"..\..\CodeUnderTest\AutogeneratedNoParameterCode.cs";

        public const string CodeToTestAtLeastOneParameterAnalyzerIgnoresGetters =
            @"..\..\CodeUnderTest\CodeToTestAtLeastOneParameterAnalyzerIgnoresGetters.cs";

        public const string CodeToTestAtLeastOneParameterAnalyzerRespectsAttributes =
            @"..\..\CodeUnderTest\CodeToTestAtLeastOneParameterAnalyzerRespectsAttributes.cs";

        public const string CodeToTestDetectingOutAndRefParameters =
            @"..\..\CodeUnderTest\CodeToTestDetectingOutAndRefParameters.cs";

        public const string CodeToTestFileMustOnlyContainOneTypeDefinition =
            @"..\..\CodeUnderTest\CodeToTestFileMustOnlyContainOneTypeDefinition.cs";

        public const string CodeToTestStaticVoidAnalyzer = @"..\..\CodeUnderTest\CodeToTestStaticVoidAnalyzer.cs";

        public const string AutogeneratedStaticVoidCode = @"..\..\CodeUnderTest\AutogeneratedStaticVoidCode.cs";

        public const string FileThatShouldBeIgnored = @"..\..\CodeUnderTest\FileThatShouldBeIgnored.cs";

        public const string CodeToTestStaticVoidAnalyzerIgnoresSetters =
            @"..\..\CodeUnderTest\CodeToTestStaticVoidAnalyzerIgnoresSetters.cs";

        public const string CodeToTestStaticVoidAnalyzerRespectsAttributes =
            @"..\..\CodeUnderTest\CodeToTestStaticVoidAnalyzerRespectsAttributes.cs";

        public const string CodeToTestMethodsWithAnd =
            @"..\..\CodeUnderTest\CodeToTestMethodsWithAnd.cs";
    }
}